# Generated by Django 3.0.2 on 2020-01-20 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(db_index=True, max_length=120)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=120)),
                ('favorite', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
