# Generated by Django 3.0.2 on 2020-01-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200121_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='notes.Category'),
        ),
    ]
