# Generated by Django 3.0.2 on 2020-01-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200121_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='posts', to='notes.Category'),
        ),
    ]
